### ISSUE TITLE
E-Bike Mont Blanc website must-do list

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#221]
We need to release on Sep-21 a final version of the Flyer for Merida to look at.

For that, we need to complete the following:
- [x] the Milestones A and B of the design
  - [ ] Milestone A: #177 
  - [x] Milestone B: #46 
- [x] enable HTTPS : #216 
  - [x] @over-e : you need to order the SSL certificate for ebikemontblanc.com domain on OVH > #217
  - [x] @damirius : what is there to setup in order to make the flyer work with HTTPS ? > #218
- [x] fill out all the labels through the translation interface
  - [x] for the home page > #219
  - [ ] for the contact page : that includes all the visible labels, the website notification label, and email labels > #220

Anything else?

**Comment by WebDevJL** [comment]
See #216 for HTTPS config.
