### ISSUE TITLE
Devis de la commande "Descriptif des modifications de Flyer V01"

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#261]
Détails de la commande : [Google Document (FR)](https://docs.google.com/document/d/160hUDFXS1mJeaQw8IzrLbpKx9lcGedWwogQ6y2WJehU)
 or [Google Document (EN)](https://docs.google.com/document/d/160hUDFXS1mJeaQw8IzrLbpKx9lcGedWwogQ6y2WJehU/edit#heading=h.ahqc3ekayfse)
1. Design  général (General Design)
2. Modifications Header (Header updates)
3. Accueil (Home page)
4. Page produit (Product page)
5.  Footer
6. Mentions légales (Legal notice page)
7. Page "Contact"
8. Paramétrage des liens externes (Parametring external links)
9. Procédure de livraison sur hébergement mutualisé (Deployment procedure on shared hosting)

**Comment by WebDevJL** [comment]
@over-e : le détail des tâches a été identifiés. Ci-dessous le lien vers le résumé de chaque userstory :

- [ ] #255 - Design  général (General Design) :  [résumé](https://github.com/Puzzlout/TrekToursFlyer/issues/255#issuecomment-281575183)
- [ ] #256 - Modifications Header (Header updates) : [résumé](https://github.com/Puzzlout/TrekToursFlyer/issues/256#issuecomment-280996716)
- [ ] #257 - Accueil (Home page) : [résumé ](https://github.com/Puzzlout/TrekToursFlyer/issues/257#issuecomment-280997541)
- [ ] #258 - Page produit (Product page) : [résumé](https://github.com/Puzzlout/TrekToursFlyer/issues/258#issuecomment-281577476)
- [ ] #259 - Footer : [résumé](https://github.com/Puzzlout/TrekToursFlyer/issues/259#issuecomment-281579898)
- [ ] #260 - Legal notice : [résumé](https://github.com/Puzzlout/TrekToursFlyer/issues/260#issuecomment-281580103)

**Comment by WebDevJL** [comment]
@over-e : la proposition de réalisation à été mise à jour avec toutes les remarques de notre rendez-vous du 23/02.

Peux-tu valider que tout y est ? Une fois validé, je te chiffre là commande. 

Merci.

**Comment by WebDevJL** [comment]
@over-e : la proposition de réalisation à été mise à jour.

Peux-tu valider que tout y est ? Une fois validé, je commence le chiffrage de la commande. 

Merci de compter ***une semaine maximum*** pour chiffrer tous les points une fois que la proposition de réalisation est confirmé.

**Comment by WebDevJL** [comment]
@over-e : Détails de la commande : [Google Document (FR)](https://docs.google.com/document/d/160hUDFXS1mJeaQw8IzrLbpKx9lcGedWwogQ6y2WJehU/edit#heading=h.9ic1apj3h3kt) => voir le paragraphe "Résumé de la réalisation".
